language: node_js
node_js:
   - "6.11.4"

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli
   - npm install -g firebase-tools

script:
   - ng build --prod

after_success:
   - firebase deploy --token $FIREBASE_TOKEN